[theme]
base = "light"
primaryColor = "#ec4899"
backgroundColor = "#fff0f6"
secondaryBackgroundColor = "#fce7f3"
textColor = "#831843"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
